name = "GlauberPT"
uuid = "cd1fa12f-b0ed-4c0a-9796-002e8e80502a"
version = "1.0.0-DEV"
authors = ["josej44 <jjdpbeat44@gmail.com> and contributors"]

[deps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
Random = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
